#ifndef RGLZ_CONFIG_H
#define RGLZ_CONFIG_H

#define RGLZ_MEMORY_PROFILE_DEFAULT_MEM_ALLOC_SIZE			16 * 1024
#define RGLZ_MEMORY_PROFILE_MIN_MEM_ALLOC_SIZE				0

#define RGLZ_APPLICATION_LOGGER_LOG_MAX_LENGTH				512 
#define RGLZ_APPLICATION_LOGGER_LOG_MAX_CUNCURRENT_LOGS 	3

#ifndef RGLZ_ENGINE_RELEASE
	#define RGLZ_ENGINE_LOGGER_DEBUG_ENABLE 1
#else
	#define RGLZ_ENGINE_LOGGER_DEBUG_ENABLE 0
#endif

#define RGLZ_ENGINE_LOGGER_TRACE_ENABLE 1
#define RGLZ_ENGINE_LOGGER_INFO_ENABLE 1
#define RGLZ_ENGINE_LOGGER_WARN_ENABLE 1
#define RGLZ_ENGINE_LOGGER_ERROR_ENABLE 1

#ifndef RGLZ_RELEASE
	#define RGLZ_LOGGER_DEBUG_ENABLE 1
#else
	#define RGLZ_LOGGER_DEBUG_ENABLE 0
#endif

#define RGLZ_LOGGER_TRACE_ENABLE 1
#define RGLZ_LOGGER_INFO_ENABLE 1
#define RGLZ_LOGGER_WARN_ENABLE 1
#define RGLZ_LOGGER_ERROR_ENABLE 1

#endif
