#ifndef RGLZ_CONFIG_H
#define RGLZ_CONFIG_H

#define RGLZ_MEMORY_PROFILE_DEFAULT_MEM_ALLOC_SIZE			16 * 1024
#define RGLZ_MEMORY_PROFILE_MIN_MEM_ALLOC_SIZE				0

#define RGLZ_APPLICATION_LOGGER_LOG_MAX_LENGTH				512 
#define RGLZ_APPLICATION_LOGGER_LOG_MAX_CUNCURRENT_LOGS 	3

#endif
